server:
  port: 8081

spring:
  application:
    name: inventory-service
  datasource:
    url: jdbc:postgresql://localhost:5432/inventory_service_db  # <-- DB name from compose
    username: nexususer                                       # <-- User from compose
    password: nexuspw                                         # <-- Password from compose
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true